version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: federated_api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    networks:
      - healthnet

  citizen_dashboard:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: citizen_dashboard
    command: ["streamlit", "run", "dashboard/citizen_app.py", "--server.port=8501"]
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - healthnet

  admin_dashboard:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: admin_dashboard
    command: ["streamlit", "run", "dashboard/admin_app.py", "--server.port=8502"]
    ports:
      - "8502:8502"
    depends_on:
      - api
    networks:
      - healthnet

networks:
  healthnet:
    driver: bridge
